Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,7 +52,13 @@ jobs:
       - name: Build
         run: |
           ./gradlew clean assembleDebug --no-daemon --stacktrace
-          cp -- app/build/outputs/apk/debug/app-debug.apk "${sanitized_artifact_file}"
+          # ファイルがあるか確認してからコピー
+          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
+            cp -- app/build/outputs/apk/debug/app-debug.apk "${sanitized_artifact_file}"
+          else
+            echo "Error: app-debug.apk not found"
+            exit 1
+          fi
 
       - name: Attest
         continue-on-error: true
